version: '3'
services:
  app:
    container_name: app
    build: .
    ports: 
      - 3000:3000 
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - dock-postgres          
    networks:
      - app-network


  dock-postgres:
    image: postgres:latest
    container_name: dock_db_postgres
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST} 
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  api:
  database_postgres:                  

# Networks to be created to facilitate communication between containers
networks:
  app-network:
    driver: bridge



